### ISSUE TITLE
Add MessageJobErrorHandler to support sending message.

### ISSUE THREAD

**Issue by Technoboy-** [apache/shardingsphere-elasticjob#1459]
To support for sending the messages when the job executes with errors, we decide to do some extensions for JobErrorHandler.
- create a new module - elasticjob-error-handler/elasticjob-error-handler-message
- load config from System parameters.
- load config from specified conf.

**Comment by viviel** [comment]
I can try it, please assign to me

**Comment by viviel** [comment]
I thought about it carefully and found that this function didn't need to be done. Because each company may use different SMS platforms, and each SMS platform has its own configuration mechanism. 

For example, some provide the rest interface or  the dependency package. users usually use the dependency rather than configure the rest interface themselves. If using the rest interface, the header parameters and URL parameters of each SMS platform may be different. In this way, it is not easy to map this information to the configuration file.

So I want to see if you have any good suggestions

@Technoboy- @terrymanu @TeslaCN

**Comment by Technoboy-** [comment]
Ok, close first.
