### ISSUE TITLE
Move OneOffJobBootstrap.triggerAllInstances into InstanceService

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1610]
There are too details export to public area, it is better to move it into internal service.

Tasks are:

- [x] Move OneOffJobBootstrap.triggerAllInstances into InstanceService
- [x] Remove getter of JobScheduler.regCenter
- [x] Add test case

**Comment by wwj-go** [comment]
please assign it to me

**Comment by wwj-go** [comment]
hi @terrymanu @TeslaCN , can we add a construct method in `OneOffJobBootstrap `just for test？
 ```
@com.google.common.annotations.VisibleForTesting
OneOffJobBootstrap() {
        jobScheduler = null;
        instanceService = null;
    }
```
As you see,it is package-private.

For the existing two construction methods, it hard to construct the instance for OneOffJobBootstrap when write a test case, because the parameter `CoordinatorRegistryCenter regCenter`.

**Comment by terrymanu** [comment]
It is better to do not add a constructor for test only
