### ISSUE TITLE
Trigger ScheduleJob duplicate execute.

### ISSUE THREAD

**Issue by Lucas-307** [apache/shardingsphere-elasticjob#1781]
### Which version of ElasticJob did you use?
3.0.0-beta

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Process
Process1: Create a ScheduleJobBootstrap with corn=0 0 0 1 1 ? 2099, shardingTotalCount=2; and JobOperateAPI.trigger it.
when this two sharding items executing.
Process2: Create the same job and trigger it again. 

### Expected behavior
Process2 do nothing.

### Actual behavior
Process2 also execute one of sharding items.

### Example codes for reproduce this issue (such as a github link).

```java
jobConfig = JobConfiguration.newBuilder(jobId, 2).cron("0 0 0 1 1 ? 2099").jobParameter("xxx").build();
jobBootstrap = new ScheduleJobBootstrap(registryCenter, new ScalingElasticJob(), jobConfig);
jobBootstrap.schedule();
jobOperateAPI.trigger(jobId);
```

**Comment by TeslaCN** [comment]
I've tested 2 cases and cannot reproduce your problem: 
1. Start Process2 while Process1 executing 2 shards. The Process2 got stuck because of waiting other shards comlete.
2. Start Process2 after Process1 finished. Reshard happened and each process got a shard. Then Process1 executed shard 1 and Process2 executed shard 2.
