### ISSUE TITLE
Does ElasticJob support zk authentication using SASL ？

### ISSUE THREAD

**Issue by fengdh23** [apache/shardingsphere-elasticjob#2099]
## Does the ElasticJob support zookeeper authentication  using SASL ？

I know the ElasticJob supports zookeeper ACL using **digest** model . 
and I want to know "Does the ElasticJob support zookeeper authentication  using SASL"?

**Comment by linghengqian** [comment]
There is no such configuration item. Do you plan to submit a PR?

**Comment by linghengqian** [comment]
For normal OpenJDK, this is largely a matter of documentation, because JAAS's SASL Java API doesn't need to deal with any third-party libraries at all, and JAAS is too conservative and backward in design. But I did find a problem with the GraalVM Native Image that warranted more investigation for #2428 .
