### ISSUE TITLE
When could you update snakeyaml version?

### ISSUE THREAD

**Issue by zts212653** [apache/shardingsphere-elasticjob#2215]
snakeyaml 1.x has bug CVE-2022-1471
when update to snakeyaml 2.0 they delete empty constructor
![image](https://user-images.githubusercontent.com/26771442/235076835-4955f526-6662-4f9d-97c9-30cc1f54e56a.png)

**Comment by linghengqian** [comment]
- There is already https://github.com/apache/shardingsphere/pull/24636#issuecomment-1475326476 as a test. 
- @zhfeng I wonder if it's possible to do this without changing the SnakeYAML version? Because Spring Team has not merged the PR I mentioned in https://github.com/apache/shardingsphere/pull/24636#pullrequestreview-1364252749.

**Comment by zhfeng** [comment]
It seems that springboot 2.7.10 should work with snakeyaml 2.0, see https://github.com/spring-projects/spring-framework/pull/30048#issuecomment-1532456180

So I think we can try to upgrade to 2.0 in shardingsphere-elasticjob. Let me prepare a PR.
