### ISSUE TITLE
几张表 没有数据

### ISSUE THREAD

**Issue by szzxl** [apache/shardingsphere-elasticjob#2250]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53551852/66858673-fd57-4963-8974-75d25272aeae)
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53551852/b226de4c-5cc0-48c5-9aa1-9f5ac0bb8862)
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53551852/0798e0ef-324d-4e8d-8c4f-c6f1943eec01)
![image](https://github.com/apache/shardingsphere-elasticjob/assets/53551852/61c6b2e9-06da-4114-a485-4d3bec3fc33b)
ui 和elasticjob版本 一致，事件追踪数据源配置就是上述几张表的地址， 目前这几张表没数据，不知道目前如何解决

**Comment by linghengqian** [comment]
- Due to the lack of maintainers of ShardingSphere Committer who know the web front-end, ShardingSphere ElasticJob UI is in a magical deadlock. I personally don't know what's wrong with the UI layer.  

- ElasticJob 3.0.3 has critical fixes for Tracing. Can you provide a reproducible example git including unit tests using ElasticJob Lite 3.0.3?

**Comment by linghengqian** [comment]
Closed due to no response.
