### ISSUE TITLE
Dependency not found ：elasticjob-spring-boot-starter

### ISSUE THREAD

**Issue by 20086996** [apache/shardingsphere-elasticjob#2365]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/41733680/0dc5d944-cfc4-41da-a386-8ed87ecaa1f6)
I can't find the dependency in the official document in the Maven

But I found this dependency，Is the official document written incorrectly？
```
<dependency>
    <groupId>org.apache.shardingsphere.elasticjob</groupId>
    <artifactId>elasticjob-lite-spring-boot-starter</artifactId>
    <version>3.0.4</version>
</dependency>
```

**Comment by linghengqian** [comment]
> But I found this dependency，Is the official document written incorrectly？

- There is no problem with the documentation. For 3.0.4, what you should check out is https://github.com/apache/shardingsphere-elasticjob/tree/3.0.4/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter .
- For the master branch, which is 3.1.0 which is not yet released, this involves https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 . Since ElasticJob Cloud has been removed, most of the dependent GAV information about ElasticJob Lite has been changed.

**Comment by linghengqian** [comment]
- Closed due to no response.
