### ISSUE TITLE
Dependency elasticjob-spring-boot-starter not found

### ISSUE THREAD

**Issue by pingguanfei** [apache/shardingsphere-elasticjob#2399]
ElasticJob / 用户手册 / 配置手册 / Spring Boot Starter

```
<dependency>
    <groupId>org.apache.shardingsphere.elasticjob</groupId>
    <artifactId>elasticjob-spring-boot-starter</artifactId>
    <version>${latest.release.version}</version>
</dependency>
```
 Maven dependency not found

**Comment by linghengqian** [comment]
- There is no problem with the documentation. For 3.0.4, what you should check out is https://github.com/apache/shardingsphere-elasticjob/tree/3.0.4/elasticjob-lite/elasticjob-lite-spring/elasticjob-lite-spring-boot-starter .
- For the master branch, which is 3.1.0 which is not yet released, this involves https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 . Since ElasticJob Cloud has been removed, most of the dependent GAV information about ElasticJob Lite has been changed.

**Comment by linghengqian** [comment]
- Closed due to no response.
