### ISSUE TITLE
elasticjob-ui is not compatible with the latest version (3.1.0-SNAPSHOT)

### ISSUE THREAD

**Issue by ooooooook** [apache/shardingsphere-elasticjob#2448]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

---

The `elasticjob-cloud` module has been removed in the latest `3.1.0-SANPSHOT.` Will `elasticjob-ui` also remove the cloud module and keep only lite? In addition, due to the refactoring of the module in version `3.1.0-SNAPSHOT`, the libraries on which ui project depends are not compatible. Is there any plan to adapt?

**Comment by linghengqian** [comment]
> Is there any plan to adapt?

- The humorous thing about this question is that I can hardly think of any existing maintainers who know how to maintain elasticjob ui. Its technical architecture is outdated from the perspective of 2024.

- From my point of view, elasticjob ui, like shardingsphere ui, is on the verge of retirement and archiving.

- Of course, the release guide of elasticjob ui is still recorded in the shardingsphere document, but this does not mean that anyone is willing to come forward to maintain it. Elasticjob does not require a ui to run.

**Comment by linghengqian** [comment]
Since elasticjob still plays a big role in shardingsphere, I would say that elasticjob itself is unlikely to be retired. But I am just a shardingsphere committer, which means that releasing new versions has little to do with me. To release a new version of elasticjob, we need to follow ASF's policy, find a release manager in PMC, initiate a vote on the mailing list, and get at least 3 votes from PMC to release it.

**Comment by ooooooook** [comment]
Indeed, ui is not necessary, I will close this issues. Having a ui interface will be more friendly to users. For the first time users of this framework, it is easy to compare it with similar products with UI interface (such as xxl-job, DolphinScheduler).

**Comment by linghengqian** [comment]
- I am not sure about the technology stack of DolphinScheduler's UI. But https://github.com/xuxueli/xxl-job is actually a typical commercial company-driven project, so they are not worried about the problem of no one maintaining it. 
- Since xxl-job uses GPL-3.0 license, it is also impossible to replace elasticjob in the https://github.com/apache/shardingsphere .
- Anyway, the community principle of ASF is always `Community Over Code`. Since I have to assume that ElasticJob UI will not find a suitable maintainer in shardingsphere PMC for a long time, if you need it, you can consider forking ElasticJob UI and refactoring it with a more modern technology stack. Whether it is Vue 3 or React 18.

**Comment by linghengqian** [comment]
As a ShardingSphere committer, I have opened https://github.com/apache/shardingsphere-elasticjob/issues/2519 .
