### ISSUE TITLE
服务器重启后，失效状态被重置成生效(不是本地覆盖注册中心)

### ISSUE THREAD

**Issue by wangjw0811** [apache/shardingsphere-elasticjob#696]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
版本2.1.5
### Expected behavior （您预期的结果是）
通过console让某个任务失效，更新服务器代码后，注册中心的任务状态不要变（不是覆盖）
~~~java
LiteJobConfiguration simpleJobRootConfig = LiteJobConfiguration.
                newBuilder(simpleJobConfig).
                disabled(true).// 作业是否启动时禁止
                overwrite(false).// 本地配置是否可覆盖注册中心配置
                build();
~~~

### Actual behavior （实际运行的结果是）
服务器重启后，失效状态被重置成生效

### Steps to reproduce the behavior （可重现问题的操作步骤）
1 console 已设置生效
![image](https://user-images.githubusercontent.com/44764995/68441486-3d063680-0209-11ea-9c58-8ffcdc2000f8.png)
![image](https://user-images.githubusercontent.com/44764995/68441568-85255900-0209-11ea-969f-d3e05fb294c7.png)
2 replace状态未成功（disable状态未修改）
![image](https://user-images.githubusercontent.com/44764995/68441619-a8e89f00-0209-11ea-9230-a4122a253a17.png)
3 将试下状态重置为空了
![image](https://user-images.githubusercontent.com/44764995/68441739-14327100-020a-11ea-89e1-c5a384b066ff.png)

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
As you describe, after restart the job service,  the ConfigurationService. Persist (LiteJobConfiguration) is unable to execute replaceJobeNode, because set the "overwrite" to false, then in the ServerService. PersistOnline (enable), "enable" is  always false by the initial setting in ZK . Please confirm step where the problem occurs again. If the problem continues to occur, I suggest you debug locally to track why the value of "enable" is inconsistent with the initial configuration in ZK.Thanks ~

无法复现你的问题。正如你描述的，重启后，由于设置overwrite为false，所以ConfigurationService.persist(LiteJobConfiguration)是无法执行replaceJobeNode的，那么在后续的ServerService.persistOnline(enable)时，enable读取就是ZK中最初设置的值false。我debug时persistOnline使用的参数始终为false。请再确认一下问题出现的环节和步骤，如果问题继续出现，建议你本地debug追踪一下enable的值和ZK中的初始配置为何不一致了。感谢~

**Comment by wangjw0811** [comment]
> As you describe, after restart the job service, the ConfigurationService. Persist (LiteJobConfiguration) is unable to execute replaceJobeNode, because set the "overwrite" to false, then in the ServerService. PersistOnline (enable), "enable" is always false by the initial setting in ZK . Please confirm step where the problem occurs again. If the problem continues to occur, I suggest you debug locally to track why the value of "enable" is inconsistent with the initial configuration in ZK.Thanks ~
> 
> 无法复现你的问题。正如你描述的，重启后，由于设置overwrite为false，所以ConfigurationService.persist(LiteJobConfiguration)是无法执行replaceJobeNode的，那么在后续的ServerService.persistOnline(enable)时，enable读取就是ZK中最初设置的值false。我debug时persistOnline使用的参数始终为false。请再确认一下问题出现的环节和步骤，如果问题继续出现，建议你本地debug追踪一下enable的值和ZK中的初始配置为何不一致了。感谢~

# 问题复现了  如果zk上的节点不做修改是没问题的，但是修改cron参数后 任务状态就被重置为空了

**Comment by wangjw0811** [comment]
发现在console修改任务时disabled和overwrite均被丢弃了，导致后续从config节点拿到的参数为false，进而使得disabled被置空
![image](https://user-images.githubusercontent.com/44764995/68643394-3f8bc780-054c-11ea-94c2-5c24faf59977.png)

**Comment by Leonidasz** [comment]
You have found the problem, you can improve it, I suggest you submit a PR. ：）

**Comment by luky116** [comment]
please assign to me, thanks

**Comment by terrymanu** [comment]
Duplicated with #537
