### ISSUE TITLE
启动“假死”

### ISSUE THREAD

**Issue by xx-ee** [apache/shardingsphere-elasticjob#731]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
elastic-job-lite-spring 2.1.5
zookeeper-3.4.10
curator 2.10.0
### Expected behavior （您预期的结果是）
重启后正常能注册和选择leader不阻塞主线程
### Actual behavior （实际运行的结果是）
 ‘xxxjob’ sleep short time until sharding completed
Registering Quartz shutdown hook.
### Steps to reproduce the behavior （可重现问题的操作步骤）
任务项目重启就会出现该问题，删除zk节点信息重启解决
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by terrymanu** [comment]
Curator 2.1.0 can support ZooKeeper 3.4.6 well, I am not test for version 3.4.10.
Can you try it?

**Comment by xx-ee** [comment]
测试中kill -9杀死springboot项目，没有优雅停止，导致后续与zk之间信息未更新，导致重启一直处于分片。

**Comment by terrymanu** [comment]
Did you configure reconcile-interval-minutes to avoid this situation?

**Comment by Simple-Coder** [comment]
yes ,but that`s not the solution for this situation.I didn`t shut the application down gracefully(such as I used command like "kill -9 'application-name' ")because of that command,that situation what is "‘xxxjob’ sleep short time until sharding completed or Registering Quartz shutdown hook....'" occurred after restarting the application.
I used to deal with that situation with deleting zk Node information.Now I shut down the application gracefully(Actually I only replicace "kill -9 pid" with "kill pid")

**Comment by Simple-Coder** [comment]
yes ,but that`s not the solution for this situation.I didn`t shut the application down gracefully(such as I used command like "kill -9 'application-name' ")because of that command,that situation what is "‘xxxjob’ sleep short time until sharding completed or Registering Quartz shutdown hook....'" occurred after restarting the application.
I used to deal with that situation with deleting zk Node information.Now I shut down the application gracefully(Actually I only replicace "kill -9 pid" with "kill pid")

**Comment by xx-ee** [comment]
yes ,but it doesn't work for this situation.I didn't shut the application down gracefully(such as I used command like "kill -9 'application-name' ")because of that command,that situation what is "‘xxxjob’ sleep short time until sharding completed or Registering Quartz shutdown hook....'" occurred after restarting the application.
I used to deal with that situation with deleting zk Node information.Now I shut down the application gracefully(Actually I only replicace "kill -9 pid" with "kill pid")

**Comment by xx-ee** [comment]
Here is an excerpt from  log where I  shut the application down gracefully:
44507 2020-06-21 11:36:53.311 Thread-2 INFO  [] [] [] [] [] [] org.apache.dubbo.remoting.transport.netty4.NettyChannel -  [DUBBO] Close netty channel [id: 0x58fcfc6a, L:/10.100.32.43:42209 - R:/10.100.32.42:9081], dubbo version: 2.7.0, current host: 10.100.32.43
44507 2020-06-21 11:36:53.311 DubboSharedHandler-thread-12 INFO  [] [] [] [] [] [] org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol -  [DUBBO] disconnected from /10.100.32.42:9081................................
44513 2020-06-21 11:36:53.317 Thread-2 INFO  [] [] [] [] [] [] org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED paused.
44515 2020-06-21 11:36:53.319 Thread-2 INFO  [] [] [] [] [] [] org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
44515 2020-06-21 11:36:53.319 Thread-2 INFO  [] [] [] [] [] [] org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED paused.
44517 2020-06-21 11:36:53.321 Thread-2 INFO  [] [] [] [] [] [] org.quartz.core.QuartzScheduler - Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
44737 2020-06-21 11:36:53.541 Quartz Shutdown-Hook balanceFlushJob INFO  [] [] [] [] [] [] org.quartz.core.QuartzScheduler - Scheduler balanceFlushJob_$_NON_CLUSTERED shutdown complete.

**Comment by wchaowu** [comment]
ZooKeeper 需要集群模式或者伪集群，单机模式有这个问题

**Comment by terrymanu** [comment]
Fixed at #798
